- name: redis
  ansible.builtin.yum: 
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
    state: installed
    disale_gpg_check: yes
    
- name: redis
  ansible.builtin.dnf: 
    name: "@redis:remi-6.2"
    state: installed

- name: update listen address
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
     
- name: Start service redis
  ansible.builtin.systemd:
    name: redis
    state: started
    enabled: yes

