# source common.sh
# print_head "Insalling Nginx"
# yum install nginx -y &>>${log_file}
# status_check $?

# #print_head "enabling nginx"
# systemctl enable nginx &>>${log_file}

# print_head "starting nginx"
# systemctl start nginx &>>${log_file}
# status_check $?

# print_head "removing existing files"
# rm -rf /usr/share/nginx/html/* &>>${log_file}
# status_check $?

# print_head "downloading frontend zip file and copy to respectivve dir"
# curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend.zip &>>${log_file}
# cd /usr/share/nginx/html &>>${log_file}
# #unzip /tmp/frontend.zip &>>${log_file}
# #status_check $?



- name: frontend setup 
  ansible.builtin.debug:
    msg: "setting up frontend"
    
- name: frontend 
  ansible.builtin.yum: 
    name: nginx
    state: installed
    
- name: Remove the old conetent
  ansible.builtin.shell: rm -rf /usr/share/nginx/html/*
  
- name: Extract foo.tgz into /var/lib/foo
  ansible.builtin.unarchive:
    src: curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html  
    remote_src: yes
