- name: Disable MySQL repository
      yum:
        name: mysql
        state: absent
        
- name: mysql
  ansible.builtin.yum: 
    name: mysql-community-server
    state: installed
    
- name: Start service mysql, if not started
  ansible.builtin.systemd:
    name: mysql
    state: restarted
    enabled: yes
    
- name: settingup password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1