- name: copy systemd module files
  ansible.builtin.copy:
    src: "{{ component }}.service"
    dest: /etc/systemd/system/"{{ component }}.service"

- name: start service
  ansible.builtin.systemd:
    name : "{{ component }}"
    state: started
    enabled : true
    daemon_reload: true